### ISSUE TITLE
Inclusion with Vim distribution

### ISSUE THREAD

**Issue by ghost** [SuneelFreimuth/vim-gemtext#1]
I have made a request to the Vim team to include Gemtext highlighting in Vim distribution, at vim/vim#8427. If you could contact them to help them in including this highlighting in Vim with this plugin, it would be of great help :)

**Comment by SuneelFreimuth** [comment]
My apologies for not noticing this sooner. I've joined the issue you opened. Thank you for helping to bring this to Vim officially!
